name: Basic CI

on:
  push:
  pull_request:

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -R
